import assert from 'node:assert/strict'
const { chromium } = await import(process.env.PLAYWRIGHT_MODULE ?? 'playwright')
const browser = await chromium.launch({headless:true})
const page = await browser.newPage({viewport:{width:1440,height:1000}})
const errors=[];page.on('pageerror', e=>errors.push(e.message))
let calls=0
await page.route('**/api/resolution', route=>{
  calls++
  return route.fulfill({json:{points:[.00001,.0001,.001,.01].map((vin_v,i)=>({vin_v,decision_time_ps:400-i*60,resolved:true,ber_noise:.1/(i+1),ber_total:.3/(i+1)})),tau_ps:26,intercept_ps:100,min_resolved_v:.00001,sigma:{noise_uv:50,offset_mv:1,total_uv:1001},markers_uv:{sigma_noise:50,sigma_offset:1000,sigma_total:1001,min_input_noise:150,min_input_total:3000},ber_target:.001,reading:'Shared measurement'}})
})
await page.goto(process.env.CONSOLE_URL ?? 'http://127.0.0.1:8771')
await page.getByLabel('M1 / M2 W (µm)',{exact:true}).waitFor()
assert.equal(await page.getByRole('navigation').getByRole('button').count(),5)
assert.equal(await page.getByLabel('M1 / M2 W (µm)',{exact:true}).count(),1)
assert.equal(await page.getByRole('button',{name:'↻ waveform',exact:true}).count(),1)
const inspector=page.getByRole('region',{name:'속성 편집기'})
assert(await inspector.isVisible())
const box=await inspector.boundingBox()
assert(box.x>900)
await page.getByRole('navigation').getByRole('button').filter({hasText:'특성 분석'}).click()
await page.getByRole('button',{name:'◎ run',exact:true}).click()
await page.getByText('Shared measurement',{exact:true}).waitFor()
const tabs=page.getByRole('tab')
await tabs.first().focus()
await page.keyboard.press('ArrowRight')
await page.getByText('Regeneration τ',{exact:true}).waitFor()
assert.equal(await page.getByRole('tab',{selected:true}).innerText(),'메타안정성')
assert.match(await page.locator('main').innerText(),/26 ps/)
await page.keyboard.press('ArrowRight')
await page.getByText('Input noise σ (gm)',{exact:true}).waitFor()
assert.match(await page.locator('main').innerText(),/50 µV/)
assert.equal(calls,1)
await page.getByRole('button',{name:'∿ VCO',exact:true}).click()
await page.getByLabel('단수 N',{exact:true}).waitFor()
assert.equal(await page.getByLabel('설계 이름',{exact:true}).count(),1)
assert.equal(await page.locator('#project-toolbar-host .project-toolbar').count(),1)
await page.screenshot({path:'/tmp/eda-vco-final.png',fullPage:true})
assert.deepEqual(errors,[])
console.log(JSON.stringify({workspacesPerDomain:5,singleDesignEditor:true,sharedResolutionRequest:calls,keyboardTabs:true,oneProjectToolbar:true,browserErrors:errors}))
await browser.close()
