import { navigate } from './navigation.mjs'
import assert from 'node:assert/strict'
import fs from 'node:fs/promises'
const { chromium } = await import(process.env.PLAYWRIGHT_MODULE ?? 'playwright')
const baseURL = process.env.CONSOLE_URL ?? 'http://127.0.0.1:8771'
const output = process.env.QA_OUTPUT ?? '/tmp/strongarm-live-qa'
await fs.mkdir(output, { recursive: true })
const browser = await chromium.launch({ headless: true })
const page = await browser.newPage({ viewport: { width: 1440, height: 1100 } })
page.setDefaultTimeout(120000)
const errors = []
page.on('pageerror', e => errors.push(e.message))
const responseFor = path => page.waitForResponse(response => new URL(response.url()).pathname === path)
await page.goto(baseURL)
await page.getByRole('checkbox').uncheck()
const measured = responseFor('/api/simulate')
const waveform = responseFor('/api/waveform')
await page.getByRole('button', { name: '▶ Run SPICE', exact: true }).click()
const comparator = await (await measured).json()
assert.equal(comparator.nominal.functional, true)
assert(comparator.nominal.decision_time_ps > 0)
assert(comparator.nominal.power_uw > 0)
const wave = await (await waveform).json()
assert(wave.n > 100)
assert(wave.t_ns.length > 100)
await navigate(page, '회로 · 파형')
await page.locator('.waveform-plot').filter({ visible: true }).waitFor()
await page.locator('.waveform-plot').filter({ visible: true }).screenshot({ path: `${output}/comparator-waveform.png` })
await page.setViewportSize({ width: 390, height: 1000 })
await page.waitForFunction(() => [...document.querySelectorAll('main canvas')].some(canvas => {
  const box = canvas.getBoundingClientRect()
  return box.width > 250 && box.right <= innerWidth
}))
await page.locator('.waveform-plot').filter({ visible: true }).screenshot({ path: `${output}/comparator-waveform-mobile.png` })
await page.getByRole('button', { name: '∿ VCO', exact: true }).click()
await page.getByRole('button', { name: '분석 메뉴', exact: true }).click()
await navigate(page, '사이징 · 튜닝')
const vcoMeasurement = responseFor('/api/vco/simulate')
await page.getByRole('button', { name: '▶ VCO 실행 (튜닝 포함)', exact: true }).click()
const vco = await (await vcoMeasurement).json()
assert.equal(vco.nominal.oscillates, true)
assert(vco.nominal.f_osc_ghz > 0)
assert(vco.tuning.points.length > 3)
await page.locator('canvas[aria-label="VCO tuning curve: frequency vs control voltage"]').waitFor()
await page.locator('canvas[aria-label="VCO tuning curve: frequency vs control voltage"]').screenshot({ path: `${output}/vco-tuning-mobile.png` })
await page.getByRole('button', { name: '분석 메뉴', exact: true }).click()
await navigate(page, 'PVT 코너')
const cornersRequest = responseFor('/api/vco/pvt')
await page.getByRole('button', { name: '◫ 45코너 실행', exact: true }).click()
const corners = await (await cornersRequest).json()
assert.equal(corners.corners.length, 45)
await page.getByRole('table', { name: 'PVT 코너 측정값' }).waitFor()
assert.equal(await page.getByRole('table', { name: 'PVT 코너 측정값' }).locator('tbody tr').count(), 5)
await page.getByRole('table', { name: 'PVT 코너 측정값' }).screenshot({ path: `${output}/vco-pvt-mobile.png` })
await page.setViewportSize({ width: 1440, height: 1100 })
await page.getByRole('button', { name: '◐ 테마', exact: true }).click()
await page.getByRole('heading', { level: 1 }).scrollIntoViewIfNeeded()
await page.screenshot({ path: `${output}/vco-pvt-desktop.png`, fullPage: true })
assert.deepEqual(errors, [])
const report = { comparator: comparator.nominal, waveformPoints: wave.n, vco: vco.nominal, tuningPoints: vco.tuning.points.length, pvtCorners: corners.corners.length, browserErrors: errors }
await fs.writeFile(`${output}/measurements.json`, JSON.stringify(report, null, 2))
console.log(JSON.stringify(report))
await browser.close()
