import assert from 'node:assert/strict'
import { navigate } from './navigation.mjs'
const { chromium } = await import(process.env.PLAYWRIGHT_MODULE ?? 'playwright')
const browser = await chromium.launch({ headless: true })
const page = await browser.newPage({ viewport: { width: 1440, height: 1000 } })
const errors=[]; page.on('pageerror', e => errors.push(e.message))
await page.goto(process.env.CONSOLE_URL ?? 'http://127.0.0.1:8772')
await page.getByRole('navigation').getByRole('button').filter({hasText:'구현 · 검증'}).click()
await page.getByRole('button', {name:'ppa-eda-agent · 실제 P&R',exact:true}).click()
await page.getByRole('combobox',{name:'실행 기록',exact:true}).selectOption('counter4__2026-08-21.json')
await page.getByRole('combobox',{name:'후보 · 반복',exact:true}).selectOption('1')
const svg=page.getByRole('img',{name:'Recorded DEF placement and routing'})
await svg.waitFor()
assert.equal(await svg.locator('rect').count(),28) // die + 27 real cells
assert((await svg.locator('line').count())>0)
assert.match(await page.locator('.physical-provenance').allTextContents().then(v=>v.join(' ')),/counter4/)
const count=await svg.locator('line').count()
await page.locator('.physical-layers input').first().uncheck()
assert((await svg.locator('line').count())<count)
await page.getByRole('button',{name:'＋',exact:true}).click()
assert.match(await svg.getAttribute('style'),/150%/)
await page.getByRole('button',{name:'전체 보기',exact:true}).click()
await page.screenshot({path:'/tmp/eda-physical-reference.png',fullPage:true})
await page.getByRole('combobox',{name:'실행 기록',exact:true}).selectOption('counter4__2026-08-30__045617.json')
await page.getByRole('combobox',{name:'후보 · 반복',exact:true}).selectOption('1')
await page.getByText('이 후보에는 저장된 셀·배선 좌표가 없습니다. 다른 후보를 선택하세요.',{exact:true}).waitFor()
assert.equal(await svg.count(),0)
assert((await page.locator('.physical-checks tbody tr').count())>20)
await page.getByRole('button',{name:'현재 설계 · GDS 초안',exact:true}).click()
assert.equal(await page.getByRole('button',{name:'▧ generate layout',exact:true}).isVisible(),true)
const measured=page.waitForResponse(r=>new URL(r.url()).pathname==='/api/layout')
await page.getByRole('button',{name:'▧ generate layout',exact:true}).click()
const generated=await (await measured).json()
assert(!generated.gds_path.startsWith('error:'))
await page.getByRole('img',{name:'Generated design GDS geometry'}).waitFor()
assert.match(await page.locator('.generated-layout').innerText(),new RegExp(generated.area_um2.toString().replace('.', '\\.')))
await page.locator('.generated-layout').screenshot({path:'/tmp/eda-current-gds.png'})
assert.deepEqual(errors,[])
console.log(JSON.stringify({realCells:27,realNets:25,layerVisibility:true,zoom:true,missingGeometryExplicit:true,recordedChecks:true,browserErrors:errors}))
await browser.close()
